name: Destroy Azure AKS With Terraform
on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
jobs: 
  AKS-Cluster-Deployment:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: AKS

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          terraform_version: latest
          cli_config_credentials_token: ${{ secrets.TFC_TOKEN_ID }}

      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Destroy Application
        run: |
         az aks get-credentials -n "cluster-unique-duckling" -g "rg-learning-garfish"
         kubectl delete -f ./AKSApp/aks-store-quickstart.yaml
         sleep 40
         rm -rf ~/.kube

      - name: Terraform destroy
        run: terraform destroy -auto-approve

      - name: Terraform Output
        run: terraform output